name: Update gist with Code::Stats stats
on:
  check_run:
      types: [completed]
      status: [success]
  schedule:
    - cron: "10 */6 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update gist
        run: python codestats_box.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          CODE_STATS_USERNAME: ${{ secrets.CODE_STATS_USERNAME }}
          STATS_TYPE: ${{ secrets.STATS_TYPE }}
